/**
 * CLI scaffolding templates for `dorisio init`.
 */

export type Framework = 'react' | 'next' | 'vanilla';
export type AuthMode = 'jwt' | 'session' | 'custom';
export type Database = 'none' | 'postgres' | 'sqlite';

export interface InitOptions {
  framework: Framework;
  auth: AuthMode;
  database: Database;
  cwd: string;
}

export interface ScaffoldFile {
  path: string;
  content: string;
}

function envPrefix(framework: Framework): string {
  if (framework === 'next') return 'NEXT_PUBLIC_';
  if (framework === 'react') return 'VITE_';
  return 'DORISIO_';
}

export function generateEnvExample(options: Pick<InitOptions, 'framework' | 'auth' | 'database'>): string {
  const p = envPrefix(options.framework);
  const apiKey = options.framework === 'vanilla' ? 'DORISIO_API_URL' : `${p}DORISIO_API_URL`;
  const lines = [
    '# Dorisio environment template — copy to .env.local and fill in values',
    `${apiKey}=http://localhost:3000`,
    `${p}DORISIO_SANDBOX=true`,
    '',
    '# Authentication',
  ];

  if (options.auth === 'jwt') {
    lines.push(`${p}DORISIO_JWT_SECRET=replace-me`);
    lines.push('# Set DORISIO_ACCESS_TOKEN at runtime after login');
  } else if (options.auth === 'session') {
    lines.push(`${p}DORISIO_SESSION_COOKIE=dorisio_session`);
  } else {
    lines.push('# Custom auth: wire your token provider in src/config/dorisio.ts');
  }

  lines.push('');
  lines.push('# Database (optional local tooling hint)');
  if (options.database === 'postgres') {
    lines.push('DATABASE_URL=postgres://user:pass@localhost:5432/dorisio');
  } else if (options.database === 'sqlite') {
    lines.push('DATABASE_URL=file:./.data/dorisio.sqlite');
  } else {
    lines.push('# DATABASE_URL=');
  }

  lines.push('');
  return lines.join('\n');
}

export function generateDorisioConfig(options: Pick<InitOptions, 'framework' | 'auth' | 'database'>): string {
  const apiExpr =
    options.framework === 'vanilla'
      ? "process.env.DORISIO_API_URL || 'http://localhost:3000'"
      : options.framework === 'next'
        ? "process.env.NEXT_PUBLIC_DORISIO_API_URL || 'http://localhost:3000'"
        : "import.meta.env.VITE_DORISIO_API_URL || 'http://localhost:3000'";

  const sandboxExpr =
    options.framework === 'vanilla'
      ? "process.env.DORISIO_SANDBOX === 'true'"
      : options.framework === 'next'
        ? "process.env.NEXT_PUBLIC_DORISIO_SANDBOX === 'true'"
        : "import.meta.env.VITE_DORISIO_SANDBOX === 'true'";

  const authComment = {
    jwt: 'JWT bearer tokens via DorisioClient.setToken()',
    session: 'Cookie/session-based auth — attach session headers in your app layer',
    custom: 'Custom auth — provide tokens through your own provider',
  }[options.auth];

  const viteRef =
    options.framework === 'react'
      ? `\n// Vite env typings (optional): add /// <reference types="vite/client" /> in a global.d.ts\n`
      : '\n';

  return `/**
 * Dorisio client configuration
 *
 * Generated by \`dorisio init\` (${options.framework} / ${options.auth} / db:${options.database}).
 * Auth mode: ${authComment}
 */
${viteRef}import { DorisioClient, createSandboxClient, type ClientConfig } from 'dorisio-sdk';

export type DorisioAuthMode = 'jwt' | 'session' | 'custom';

export interface DorisioAppConfig {
  baseUrl: string;
  auth: DorisioAuthMode;
  database: 'none' | 'postgres' | 'sqlite';
  mode: 'production' | 'sandbox';
}

export const dorisioConfig: DorisioAppConfig = {
  baseUrl: ${apiExpr},
  auth: '${options.auth}',
  database: '${options.database}',
  mode: ${sandboxExpr} ? 'sandbox' : 'production',
};

/**
 * Create a configured Dorisio client for this app.
 */
export function createAppDorisioClient(token?: string): DorisioClient {
  if (dorisioConfig.mode === 'sandbox') {
    return createSandboxClient() as unknown as DorisioClient;
  }

  const config: ClientConfig = {
    baseUrl: dorisioConfig.baseUrl,
    token,
    mode: 'production',
  };

  return new DorisioClient(config);
}
`;
}

export function generateUseCreatorHook(framework: Framework): string {
  if (framework === 'vanilla') {
    return `/**
 * Creator helpers for vanilla TypeScript apps.
 *
 * Generated by \`dorisio init\`.
 */

import type { Creator, CreatorProfile } from 'dorisio-sdk';
import { createAppDorisioClient } from '../config/dorisio';

export async function fetchCreator(creatorId: string): Promise<Creator | null> {
  const client = createAppDorisioClient();
  try {
    return await client.getCreator(creatorId);
  } catch {
    return null;
  }
}

export async function fetchCreatorProfile(username: string): Promise<CreatorProfile | null> {
  const client = createAppDorisioClient();
  try {
    return await client.getCreatorProfile(username);
  } catch {
    return null;
  }
}
`;
  }

  return `/**
 * useCreator — local app hook wrapping dorisio-sdk/react.
 *
 * Generated by \`dorisio init\` for ${framework}.
 */

'use client';

export { useCreator } from 'dorisio-sdk/react';
`;
}

export function generateReadmeSnippet(options: InitOptions): string {
  return `# Dorisio init

Scaffolded with \`dorisio init\` (${options.framework}, auth=${options.auth}, db=${options.database}).

## Next steps

1. Copy \`.env.example\` to \`.env.local\` and fill in values
2. Install the SDK: \`npm install dorisio-sdk\`
3. Import \`createAppDorisioClient\` from \`./src/config/dorisio\`
`;
}

/**
 * Build the file set written by \`dorisio init\`.
 */
export function buildScaffoldFiles(options: InitOptions): ScaffoldFile[] {
  const hookPath =
    options.framework === 'vanilla' ? 'src/lib/creators.ts' : 'src/hooks/useCreator.ts';

  return [
    { path: 'src/config/dorisio.ts', content: generateDorisioConfig(options) },
    { path: hookPath, content: generateUseCreatorHook(options.framework) },
    { path: '.env.example', content: generateEnvExample(options) },
    { path: '.env.local', content: generateEnvExample(options) },
    { path: 'DORISIO_SETUP.md', content: generateReadmeSnippet(options) },
  ];
}
